---
name: cf-warden-mysql
director_uuid: PLACEHOLDER-DIRECTOR-UUID
releases:
  - name: cf-mysql
    version: latest

properties:
  app_domains: (( merge || ["bosh-lite.com"] ))
  domain: (( merge || "bosh-lite.com" ))
  nats:
    machines: [10.244.0.6]
    password: nats
    port: 4222
    user: nats
  cf:
    admin_username: admin
    admin_password: admin
    skip_ssl_validation: true

jobs:
  - name: mysql_z1
    properties:
      <<: (( merge || nil ))
      admin_password: password
      database_startup_timeout: 600
      bootstrap_endpoint:
        username: username
        password: password
  - name: cf-mysql-broker_z1
    properties:
      <<: (( merge || nil ))
      auth_password: password
      auth_username: admin
      cookie_secret: 94046872-2602-4ca6-8d07-8b0da9762477
      skip_ssl_validation: true
      services:
      - name: p-mysql
        dashboard_client:
          secret: p-mysql-secret
        plans:
        - name: 100mb
          max_storage_mb: 10
        - name: 1gb
          max_storage_mb: 20
  - name: proxy_z1
    properties:
      <<: (( merge || nil ))
      proxy:
        <<: (( merge || nil ))
        api_username: username
        api_password: password
