director_uuid: REPLACE_WITH_YOUR_DIRECTOR_UUID

meta:
  # Used as a prefix for the deployment name
  #
  # e.g. `environment: cf-tabasco` makes a deployment named cf-tabasco-mysql
  environment: REPLACE_WITH_YOUR_ENVIRONMENT_NAME

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
networks:
- name: mysql1
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved:
    - 10.0.0.2-10.0.0.109
    - 10.0.0.130-10.0.0.254
    static:
    - 10.0.0.120
    - 10.0.0.121
    - 10.0.0.122
    - 10.0.0.123
    - 10.0.0.124
    dns:
    - 10.0.0.3
    - 8.8.8.8
    cloud_properties:
      name: REPLACE_WITH_YOUR_SUBNET_NAME #This should match your vSphere network name, e.g. "VM Network".
- name: mysql2
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    reserved:
    - 10.0.1.2-10.0.1.109
    - 10.0.1.130-10.0.1.254
    static:
    - 10.0.1.120
    - 10.0.1.121
    - 10.0.1.122
    - 10.0.1.123
    - 10.0.1.124
    dns:
    - 10.0.1.3
    - 8.8.8.8
    cloud_properties:
      name: REPLACE_WITH_YOUR_SUBNET_NAME_2
- name: mysql3
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    reserved:
    - 10.0.2.2-10.0.2.109
    - 10.0.2.130-10.0.2.254
    static:
    - 10.0.2.120
    - 10.0.2.121
    - 10.0.2.122
    - 10.0.2.123
    - 10.0.2.124
    dns:
    - 10.0.2.3
    - 8.8.8.8
    cloud_properties:
      name: REPLACE_WITH_YOUR_SUBNET_NAME_3
- name: compilation
  subnets:
  - range: 10.0.3.0/24
    gateway: 10.0.3.1
    reserved:
    - 10.0.3.2-10.0.3.169
    - 10.0.3.190-10.0.3.254
    static:
    - 10.0.3.170-10.0.3.174
    dns:
    - 10.0.3.3
    - 8.8.8.8
    cloud_properties:
      name: REPLACE_WITH_YOUR_SUBNET_NAME_4

properties:
  cf:
    admin_username: REPLACE_WITH_YOUR_CF_ADMIN_USERNAME
    admin_password: REPLACE_WITH_YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: REPLACE_WITH_TRUE_OR_FALSE # True if you don't have a trusted SSL certificate, false if you do
  domain: REPLACE_WITH_YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-mysql.external_domain
  app_domains:
  - REPLACE_WITH_YOUR_CF_APPS_DOMAIN
  nats:
    machines:
      - REPLACE_WITH_NATS_IP_ADDRESS_FROM_CF_RELEASE
    password: REPLACE_WITH_NATS_PASSWORD_FROM_CF_RELEASE
    user: nats
    port: 4222
  # A multi-AZ VSphere environment can be distributed across different datacenters and/or clusters
  datacenters:
  - name: z1
    datacenter_name: REPLACE_WITH_YOUR_FIRST_DATACENTER
    clusters:
    - REPLACE_WITH_YOUR_FIRST_CLUSTER:
        resource_pool: REPLACE_WITH_YOUR_FIRST_RESOURCE_POOL
  - name: z2
    datacenter_name: REPLACE_WITH_YOUR_SECOND_DATACENTER
    clusters:
    - REPLACE_WITH_YOUR_SECOND_CLUSTER:
        resource_pool: REPLACE_WITH_YOUR_SECOND_RESOURCE_POOL
  - name: z3
    datacenter_name: REPLACE_WITH_YOUR_THIRD_DATACENTER
    clusters:
    - REPLACE_WITH_YOUR_THIRD_CLUSTER:
        resource_pool: REPLACE_WITH_YOUR_THIRD_RESOURCE_POOL

jobs:
- name: proxy_z1
  properties:
    proxy:
      api_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP # Used for basic auth in front of proxy api
      api_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
- name: mysql_z1
  properties:
    admin_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process
    bootstrap_endpoint:
      username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP
      password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
- name: cf-mysql-broker_z1
  properties:
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP #eg. cc
    auth_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    cookie_secret: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    services:
    - name: p-mysql
      dashboard_client:
        secret: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
