director_uuid: REPLACE_WITH_YOUR_DIRECTOR_UUID

meta:
  # Used as a prefix for the deployment name
  #
  # e.g. `environment: cf-tabasco` makes a deployment named cf-tabasco-mysql
  environment: REPLACE_WITH_YOUR_ENVIRONMENT_NAME

# NOTE:
# Replace 10.0.{0,1,2} part of the octet
# with your network configuration
networks:
- name: mysql1
  type: manual
  subnets:
  - range: 10.10.32.0/24
    reserved:
      - 10.10.32.2 - 10.10.32.9
      - 10.10.32.130 - 10.10.32.254
    static:
      - 10.10.32.10 - 10.10.32.14
    gateway: 10.10.32.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql1 ))
- name: mysql2
  type: manual
  subnets:
  - range: 10.10.33.0/24
    reserved:
      - 10.10.33.2 - 10.10.33.9
      - 10.10.33.130 - 10.10.33.254
    static:
      - 10.10.33.10 - 10.10.33.14
    gateway: 10.10.33.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql2 ))
- name: mysql3
  type: manual
  subnets:
  - range: 10.10.34.0/24
    reserved:
      - 10.10.34.2 - 10.10.34.9
      - 10.10.34.130 - 10.10.34.254
    static:
      - 10.10.34.10 - 10.10.34.14
    gateway: 10.10.34.1
    dns:
      - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
    cloud_properties:
      subnet: (( properties.template_only.aws.subnet_ids.mysql3 ))
- name: compilation
  type: manual
  subnets:
    - range: 10.10.35.0/24
      name: default_unused
      reserved:
        - 10.10.35.2 - 10.10.35.9
        - 10.10.35.130 - 10.10.35.254
      static:
        - 10.10.35.10 - 10.10.35.14
      gateway: 10.10.35.1
      dns:
        - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
      cloud_properties:
        subnet: (( properties.template_only.aws.subnet_ids.compilation ))

properties:
  cf:
    # these come from your cf-release manifest
    admin_username: REPLACE_WITH_YOUR_CF_ADMIN_USERNAME
    admin_password: REPLACE_WITH_YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: REPLACE_WITH_TRUE_OR_FALSE # True if you don't have a trusted SSL certificate, false if you do

  domain: REPLACE_WITH_YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-msyql.external_domain.
  app_domains:
  - REPLACE_WITH_YOUR_CF_APPS_DOMAIN
  nats:
    user: nats
    password: REPLACE_WITH_NATS_PASSWORD_FROM_CF_RELEASE
    machines:
      - REPLACE_WITH_NATS_IP_ADDRESS_FROM_CF_RELEASE
    port: 4222

  template_only:
    aws:
      availability_zone: REPLACE_WITH_YOUR_AWS_AVAILABILITY_ZONE_1 #From the EC2 page of the AWS console, like us-east-1a
      availability_zone2: REPLACE_WITH_YOUR_AWS_AVAILABILITY_ZONE_2 #From the EC2 page of the AWS console, like us-east-1b
      availability_zone3: REPLACE_WITH_YOUR_AWS_AVAILABILITY_ZONE_3 #From the EC2 page of the AWS console, like us-east-1c
      subnet_ids:
        # From VPC/Subnets page of AWS console. Availability zone must match the value set above.
        mysql1: REPLACE_WITH_YOUR_SUBNET_ID_1
        mysql2: REPLACE_WITH_YOUR_SUBNET_ID_2
        mysql3: REPLACE_WITH_YOUR_SUBNET_ID_3
        compilation: REPLACE_WITH_YOUR_COMPILATION_SUBNET


jobs:
# Jobs for cf-mysql-release are below
- name: mysql_z1
  properties:
    admin_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process
    bootstrap_endpoint:
      username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP
      password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP

- name: cf-mysql-broker_z1
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP # eg. cc
    auth_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    cookie_secret: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
    services:
      - name: p-mysql
        dashboard_client:
          secret: REPLACE_WITH_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
        plans:
        - name: REPLACE_WITH_YOUR_PLAN_NAME
          max_storage_mb: REPLACE_WITH_PLAN_SIZE_IN_MB

- name: proxy_z1
  release: cf-mysql
  properties:
    proxy:
      api_username: REPLACE_WITH_A_USERNAME_YOU_MAKE_UP
      api_password: REPLACE_WITH_A_PASSWORD_YOU_MAKE_UP
