jobs:
- name: cf-mysql-broker_z1
  properties:
    services:
    - name: p-mysql
      plans:
      - name: 100mb
        id: ab08f1bc-e6fc-4b56-a767-ee0fea6e3f20
        description: Shared MySQL Server
        max_storage_mb: 100
        max_user_connections: 20
        metadata:
          costs:
          - amount:
              usd: 0.0
            unit: MONTH
          bullets:
            - Shared MySQL server
            - 100 MB storage
            - 20 concurrent connections
          displayName: "100 MB"
      - name: 1gb
        id: 11d0aa36-dcec-4021-85f5-ea4d9a5c8342
        description: Shared MySQL Server
        max_storage_mb: 1000
        max_user_connections: 40
        metadata:
          costs:
          - amount:
              usd: 0.0
            unit: MONTH
          bullets:
            - Shared MySQL server
            - 1000 MB storage
            - 40 concurrent connections
          displayName: "1 GB"
